Updates (Look at description)
thoth-tech/CourseFlow pull request #29
Opened 2023-09-09 07:51 UTC by SoVinhou

This update includes:
- Ability for user to now create account
- Ability for user to now Sign In with their email accounts
- Ability for user to sign in using their google account (using google oauth)
- Add user data to database when they create account into Firebase Database
- Updated Designs
- Reset Password Page and ability for user to reset password through their email address

2023-09-14 03:27 UTC, Vortrox requested changes
We need to merge PR #28 first before merging this

2023-09-15 09:02 UTC, cmarktopher commented on Frontend/CourseFlow_Login_Form/Firebase Account/Account.txt
Might not be a good idea to include these.

2023-09-15 09:02 UTC, cmarktopher commented on Frontend/CourseFlow_Login_Form/src/environments/environment.prod.ts
Same with the account details, might not want to include these here either.

2023-09-15 09:03 UTC, cmarktopher commented on Frontend/CourseFlow_Login_Form/src/environments/environment.ts
Same with the account details, might not want to include these here either.

2023-09-18 09:52 UTC, SoVinhou commented
I have made the requested changes:
- resetted courseflow firebase password
- hide API keys (Only students with access to account which will be provided privately) will be able to run application

2023-09-18 12:08 UTC, cmarktopher approved these changes
Review of PR:

- Accounts and keys were updated and information removed from recent commit.
- Tested features locally.
- Email/Password based sign up works with email verification also working.
- Google OAuth is also working.
- Reset password with reset email link also working correctly. New password works with login.

2023-09-18 12:09 UTC, cmarktopher commented
PR #28 seems to have been merged already.

2023-09-18 12:12 UTC, merged

2023-09-25 10:11 UTC, SoVinhou commented
Overall Video Demonstration of the pull request:
https://youtu.be/UXUS8YocjVo