Create timetable-view.html
thoth-tech/CourseFlow pull request #3
Opened 2023-04-06 23:43 UTC by keyruhn

Current progress on timetable view file

2023-04-06 23:59 UTC, keyruhn commented
All of the current progress on the front-end of CourseFlow

2023-04-07 01:09 UTC, Vortrox commented on Front-End/assets/blank.txt
What's this for?

2023-04-07 01:13 UTC, Vortrox requested changes

2023-04-07 01:13 UTC, Vortrox commented on Front-End/assets/blank.txt
Maybe we should remove this if it's not being used

2023-05-24 11:34 UTC, Vortrox commented
Merging for end of trimester handover

2023-05-24 11:50 UTC, Vortrox approved these changes

2023-05-24 11:53 UTC, merged